### ISSUE TITLE
Error when 'progress = TRUE' in dynEGA for group level 

### ISSUE THREAD

**Issue by gitprodia** [hfgolino/EGAnet#108] opened 2023-01-18 10:09 UTC
When I try to run dynEGA for group level analysis on my Mac I get the following error:
```
Level: Group...Error in seq.default(split_computations, total_computations, split_computations) : 
  wrong sign in 'by' argument
```

I found out this error is somehow related to the progress bar, which is TRUE by default. When I run with `'progress = FALSE'` the error doesn't show up and the function runs normally.

**Comment by hfgolino** [comment] 2023-01-18 16:57
Thanks for the heads-up!

Cheers,

Hudson



*Hudson Golino*
*Associate Professor*
*Department of Psychology*

*E* ***@***.*** ***@***.***>

*University of Virginia*

1023 Millmont St, Office 115
Charlottesville, VA 22903




Em qua., 18 de jan. de 2023 às 05:10, IDEA-RiSCo data repository <
***@***.***> escreveu:

**Comment by AlexChristensen** [comment] 2023-07-12 18:11
@gitprodia, this issue was likely caused by the fact that groups rarely ever exceed cores being used. There will only be a progress bar when `level` includes `"individual"` in the future: https://github.com/hfgolino/EGAnet/tree/no-cpp

Closing because this issue will be resolved in the next update

**Closed by AlexChristensen** 2023-07-12 18:11 UTC
Labels: bug, in-progress
